stages:
  # - lint
  - test
  - build
  # - deploy

lint:
  stage: test
  image: node:8
  script:
    - yarn run lint
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - ./node_modules/

test:
  stage: test
  image: node:8
  script:
    - yarn run test

build:
  stage: build
  image: node:8
  script:
    - yarn run build
  only:
    - master
  artifacts:
    paths:
      - ./build/
