stages:
  - test
  - build
  - deploy

image: node:8

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - yarn install

lint:
  stage: test
  allow_failure: true
  script:
    - yarn lint

lint-critical:
  stage: test
  allow_failure: true
  script:
    - yarn lint:critical

test:
  stage: test
  allow_failure: true
  script:
    - yarn test

build:
  stage: build
  script:
    - yarn build
  only:
    - master
  artifacts:
    paths:
      - ./build/

pages:
  stage: deploy
  script:
    - mv build public
  # only:
  #   - master

# deploy:
#   stage: deploy
#   script:
#     - echo "deploying..."
#   environment:
#       name: production
#       url: '.....'
#   only:
#     - master
