stages:
  - test
  - build
  - deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/

before_script:
  - yarn install

lint:
  stage: test
  tags:
    - docker
  image: node:8
  allow_failure: true
  script:
    - yarn lint

lint-critical:
  stage: test
  tags:
    - docker
  image: node:8
  # allow_failure: true
  script:
    - yarn lint:critical

test:
  stage: test
  tags:
    - docker
  image: node:8
  allow_failure: true
  script:
    - yarn test

build:
  stage: build
  tags:
    - docker
  image: node:8
  script:
    - yarn build
  artifacts:
    paths:
      - ./build/

deploy:
  stage: deploy
  dependencies:
    - build
  tags:
    - docker
  image: node:8
  only:
    - master
  script:
    - ./scripts/upload.sh ./build/
